# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

balancete = Balancete.create
grupo = balancete.itens.create(nome: 'ATIVO')
subgrupo = grupo.itens.create(nome: 'ATIVO CIRCULANTE')
sintetica1 = subgrupo.itens.create(nome: 'DISPONIBILIDADES')
sintetica1.itens.create(nome: 'Caixa', saldo_anterior_valor: 1000.0, debito_valor: 14000.0, credito_valor: 6034.5)
sintetica1.itens.create(nome: 'Banco', saldo_anterior_valor: 4555.01, debito_valor: 0, credito_valor: 287)
sintetica1.itens.create(nome: 'Aplicações Financeiras')
sintetica2 = subgrupo.itens.create(nome: 'CRÉDITOS (Valor a Receber)')
sintetica2.itens.create(nome: 'Clientes', saldo_anterior_valor: 0, debito_valor: 6000, credito_valor: 0)
sintetica2.itens.create(nome: 'Créditos Diversos', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica2.itens.create(nome: 'Emprestimos', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica2.itens.create(nome: 'Imposto a Recuperar', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica2.itens.create(nome: '(-) Duplicatas Descontadas', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica2.itens.create(nome: '(-) Provisão para Créditos de Liquidação Duvidosa', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica3 = subgrupo.itens.create(nome: 'ESTOQUE')
sintetica3.itens.create(nome: 'Mercadorias para Revenda', saldo_anterior_valor: 811838.64, debito_valor: 11774.5, credito_valor: 500)
sintetica3.itens.create(nome: 'Matéria-Prima', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)

subgrupo2 = grupo.itens.create(nome: 'ATIVO NÂO CIRCULANTE')
sintetica4 = subgrupo2.itens.create(nome: 'ATIVO REALIZÁVEL A LONGO PRAZO')
sintetica4.itens.create(nome: 'Clientes', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica4.itens.create(nome: 'Créditos Diversos', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica4.itens.create(nome: 'Emprestimos', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica5 = subgrupo2.itens.create(nome: 'INVESTIMENTOS')
sintetica5.itens.create(nome: 'Aplicações em Coligadas e Controladas', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica5.itens.create(nome: 'Aplicações em Outras Empresas', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica5.itens.create(nome: 'Imóveis para Renda', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6 = subgrupo2.itens.create(nome: 'IMOBILIZADO')
sintetica6.itens.create(nome: 'Terrenos', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: 'Construções Prediais', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: 'Instalações', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: 'Máquinas e Equipamentos', saldo_anterior_valor: 12000, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: 'Móveis e Utensilios', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: 'Veículos', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: 'Equipamentos de Informática', saldo_anterior_valor: 1500, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: '(-) Depreciação Acumulada - Terrenos', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: '(-) Depreciação Acumulada - Construções Prediais', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: '(-) Depreciação Acumulada - Instalações', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: '(-) Depreciação Acumulada - Máquinas e Equipamentos', saldo_anterior_valor: 4800, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: '(-) Depreciação Acumulada - Móveis e Utensilios', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: '(-) Depreciação Acumulada - Veículos', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica6.itens.create(nome: '(-) Depreciação Acumulada - Equipamentos de Informática', saldo_anterior_valor: 600, debito_valor: 0, credito_valor: 0)
sintetica7 = subgrupo2.itens.create(nome: 'DIFERIDO')
sintetica7.itens.create(nome: 'Gastos Pré-operacionais', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica7.itens.create(nome: '(-) Amortização Acumulada - Gastos Pré-operacionais', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica8 = subgrupo2.itens.create(nome: 'INTANGÍVEL')
sintetica8.itens.create(nome: 'Marcas e Patentes', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
sintetica8.itens.create(nome: '(-) Amortização Acumulada - Marcas e Patentes', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
#sintetica4.itens.create(nome: '', saldo_anterior_valor: 0, debito_valor: 0, credito_valor: 0)
